import React from 'react';

import type { Metadata } from 'next';

import 'bootstrap/dist/css/bootstrap.css';

import './globals.css';

export const metadata: Metadata = {
  title: 'Realtime Chat Room',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
